### PR TITLE
Bugfix: `Worksheet.addSheetData` corrupting Xlsx file saved in Excel before

### LINKED ISSUE #16: [BUG] `Worksheet.addSheetData` corrupts Xlsx file if file was saved before via MS Excel
**Describe the bug**
When saving an Xlsx file in MS Excel, some Xml-Children are added by default to the SpreadsheetDocument if they didn't exist yet in it. That is, among others, `pageMargins`. Atm. `Worksheet.addSheetData` appends the `SheetData` to the Worksheet – therefore, it will always be attached at the end. Unfortunately, Excel errors if `pageMargins` is not the last child.

**To Reproduce**
1. Create a new Xlsx file:
```f#
#r "nuget: FSharpSpreadsheetML"

open FSharpSpreadsheetML

let path =
    System.Environment.GetFolderPath(System.Environment.SpecialFolder.UserProfile)
    |> fun fp -> System.IO.Path.Combine(fp, "mySpreadsheet.xlsx")

let doc = Spreadsheet.init "mySheet" path

let sd = Spreadsheet.tryGetSheetBySheetName "mySheet" doc |> Option.get

SheetData.appendValueToRowAt None 1u "Hello, World!" sd

Spreadsheet.close doc
```
2. Open the file in MS Excel and save it.
3. Replace the `SheetData`:
```f#
let doc = Spreadsheet.fromFile path true

let sd = Spreadsheet.tryGetSheetBySheetName "mySheet" doc |> Option.get
let wsp = Spreadsheet.tryGetWorksheetPartBySheetName "mySheet" doc |> Option.get
let ws = Worksheet.get wsp

if Worksheet.hasSheetData ws then
    ws.RemoveChild(Worksheet.getSheetData ws)
    |> ignore

Worksheet.addSheetData sd ws

Spreadsheet.close doc
```
4. Open the file in Excel again. See Error.

**Expected behavior**
No change in the file's structure. No Error when opening it with Excel.

**Screenshots**
image
Xml structure of healthy file.

image
Xml structure of Error-throwing file.

**OS and framework information (please complete the following information):**
 - OS: Win10Pro 
 - OS Version: 10.0, Build 19042
 - .Net core SDK version: 5.0.403

**Additional information**
This most probably causes https://github.com/nfdi4plants/ISADotNet/issues/49

### LINKED ISSUE #49: [BUG] `Worksheet.setSheetData` corrupts Xlsx files saved in MS Excel before
**Describe the bug**
If an Xlsx file that has been opened and saved in MS Excel before is edited via `Worksheet.setSheetData` and saved, the file gets corrupted and the `SheetData` of this file's worksheet cannot be obtained anymore.

**To Reproduce**
1. Create a new Xlsx file via FSharpSpreadsheetML and save it:
```f#
#r "nuget: FSharpSpreadsheetML"

open FSharpSpreadsheetML

let path =
    System.Environment.GetFolderPath(System.Environment.SpecialFolder.UserProfile)
    |> fun fp -> System.IO.Path.Combine(fp, "mySpreadsheet.xlsx")

let doc = Spreadsheet.init "mySheet" path

let sd = Spreadsheet.tryGetSheetBySheetName "mySheet" doc |> Option.get

SheetData.appendValueToRowAt None 1u "Hello, World!" sd

Spreadsheet.close doc
```
2. Open the file in MS Excel and save it.
3. Replace the sheet with the same sheet:
```f#
let doc = Spreadsheet.fromFile path true

let sd = Spreadsheet.tryGetSheetBySheetName "mySheet" doc |> Option.get
let wsp = Spreadsheet.tryGetWorksheetPartBySheetName "mySheet" doc |> Option.get
let ws = Worksheet.get wsp
setSheetData sd ws

Spreadsheet.close doc
```
4. Open file again MS Excel
5. See error

**Expected behavior**
Uncorrupted file.

**OS and framework information (please complete the following information):**
 - OS: Win10 Pro
 - OS Version: 10.0, Build 19042
 - .Net core SDK version: 5.0.403

### PR DESCRIPTION
**Pull request by omaus**
- Fixes #16 
- Indirectly fixes https://github.com/nfdi4plants/ISADotNet/issues/49
- Adds `setSheetData` function
- Adds `replaceSheetData` function
- Some typos fixed, phrasing and wording unified

### CODE REVIEW

File: src/FSharpSpreadsheetML/Workbook.fs [hunk 1]
```diff
@@ -123,3 +123,21 @@ module WorkbookPart =
 
         sheets.AppendChild(sheet) |> ignore
         workbookPart
+
+    /// Replaces the SheetData of the Sheet with the given sheetname.
+    let replaceSheetData (sheetName : string) (data : SheetData) (workbookPart : WorkbookPart) =
```
Comment (HLWeil) [inline src/FSharpSpreadsheetML/Workbook.fs]: Rename to "replaceSheetDataByName"

**Review by HLWeil — CHANGES_REQUESTED** [review]
